### ISSUE TITLE
服务器端的安装和配置能否写一些从零开始的内容呢？

### ISSUE THREAD

**Issue by itrilogy** [whyiyhw/chatgpt-wechat#10]
能不能给出详细的依赖环境安装步骤、下载代码、配置、启用服务的较为具体的流程呢？

**Comment by dd404x** [comment]
我感觉文档已经写的很清楚了，建议多读几遍，已成功~
![image](https://user-images.githubusercontent.com/19923974/225542834-c494e022-1cbf-40c3-8b4e-b1d5017c2d8b.png)

**Comment by whyiyhw** [comment]
> 能不能给出详细的依赖环境安装步骤、下载代码、配置、启用服务的较为具体的流程呢？

毕竟这是是GitHub，基础的 git 跟 docker 怎么用都需要详细描述，后面的网络代理部分就更加搞不清楚了

**Comment by itrilogy** [comment]
我这就学……

从 Windows 版邮件发送

发件人: whyiyhw
发送时间: 2023年3月18日 14:23
收件人: whyiyhw/chatgpt-wechat
抄送: itrilogy; Author
主题: Re: [whyiyhw/chatgpt-wechat] 服务器端的安装和配置能否写一些从零开始的内容呢？ (Issue #10)

能不能给出详细的依赖环境安装步骤、下载代码、配置、启用服务的较为具体的流程呢？
毕竟这是是GitHub，基础的 git 跟 docker 怎么用都需要详细描述，后面的网络代理部分就更加搞不清楚了
