### ISSUE TITLE
   大佬，这2个端口可以改吗？ 可以自己定义吗

### ISSUE THREAD

**Issue by azz212** [whyiyhw/chatgpt-wechat#101]
version: '3'

services:
  web:
    container_name: chat-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8887:8887"
    大佬，这2个端口可以改吗？ 可以自己定义吗

**Comment by whyiyhw** [comment]
可以的，比如 "18888:8888"
