### ISSUE TITLE
我端口是8080 如何修改配置

### ISSUE THREAD

**Issue by azz212** [whyiyhw/chatgpt-wechat#103]
请确认 ip:8887 端口对外开放，如果是云服务器，需要在云服务器的安全组中，开放 8887 端口
验证方式 curl --location http://{host}:8887 -v ，如果返回 400 响应就说明端口已开放，服务已经启动成功了

大佬，这一步一直不通过，我端口是8080 如何修改配置？按照上面的指导将docker文件 修改为8080端口，是否可以？
version: '3'

services:
  web:
    container_name: chat-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8887:8080"

**Comment by whyiyhw** [comment]
- "8080:8887" 再试试呢
