### ISSUE TITLE
微信客服错误

### ISSUE THREAD

**Issue by azz212** [whyiyhw/chatgpt-wechat#104]
}
客服消息 -------------------------------------
客服消息 Token: ENCEp3YQRDV/xxxxxxxHdPZfsJDZTUEreTcEot2pJA1jui OpenKfID: wkWUBoNQAAETZxxxxxHGbu_aGJQ
客服消息 获取body err: WorkwxClientError { Code: 41001, Msg: "access_token missing, hint: [1705048475107081959400113], from ip: 43.129.186.111, more info at https://open.work.weixin.qq.com/devtool/query?e=41001" }
incoming message: RxMessage { FromUserID: "sys", SendTime: 1705048729000000000, MsgType: "event", MsgID: 0, AgentID: 0, Event: "kf_account_auth_change", ChangeType: "", Raw: "<xml><ToUserName><![CDATA[ww590aa0af95637b5b]]></ToUserName><FromUserName><![CDATA[sys]]></FromUserName><CreateTime>1705048729</CreateTime><MsgType><![CDATA[event]]></MsgType><Event><![CDATA[kf_account_auth_change]]></Event><AuthDelOpenKfId><![CDATA[wkWUBoNQAAETZMsYUGmXPdyHGbu_aGJQ]]></AuthDelOpenKfId></xml>" }
incoming message: RxMessage { FromUserID: "sys", SendTime: 1705048905000000000, MsgType: "event", MsgID: 0, AgentID: 0, Event: "kf_account_auth_change", ChangeType: "", Raw: "<xml><ToUserName><![CDATA[ww590aa0af95637b5b]]></ToUserName><FromUserName><![CDATA[sys]]></FromUserName><CreateTime>1705048905</CreateTime><MsgType><![CDATA[event]]></MsgType><Event><![CDATA[kf_account_auth_change]]></Event><AuthAddOpenKfId><![CDATA[wkWUBoNQAAETZMsYUGmXPdyHGbu_aGJQ]]></AuthAddOpenKfId></xml>" }
大佬做微信客服的话，报下面的错误，并且微信客服配置界面变了，没有secret  token 之类的了

**Comment by whyiyhw** [comment]
好的，我周末修复掉

**Comment by whyiyhw** [comment]
已修复，配置与文档已更新
