### ISSUE TITLE
clear命令怎么失效了

### ISSUE THREAD

**Issue by azz212** [whyiyhw/chatgpt-wechat#107]
![Screenshot_20240116_173724_com.tencent.mm.jpg](https://user-images.githubusercontent.com/33420910/296999724-e57debee-06ab-4272-9dfe-12b2cbe491d8.jpg)

大佬看看，失效了，那个timeout怎么设置？

**Comment by whyiyhw** [comment]
如果用3.5的话，把TotalToken 跟 MaxToken 设置小一些

**Comment by azz212** [comment]
这个还没解决吗？大佬
