### ISSUE TITLE
建议在配置文件增加企业微信api地址 

### ISSUE THREAD

**Issue by hyzaw** [whyiyhw/chatgpt-wechat#110]
由于有些用户是家庭ip，需要服务器ip来做白名单中转，查询go-workwx文档得到 https://pkg.go.dev/github.com/xen0n/go-workwx#example-Workwx 可以配置企业微信api地址，建议增加该配置项

**Comment by whyiyhw** [comment]
已支持，请查看 chat/service/chat/api/etc/chat-api.yaml.complete.bak
