### ISSUE TITLE
企业微信客服报错

### ISSUE THREAD

**Issue by hyzaw** [whyiyhw/chatgpt-wechat#111]
incoming message: RxMessage { FromUserID: "", SendTime: 1711176915000000000, MsgType: "event", MsgID: 0, AgentID: 0, Event: "kf_msg_or_event", ChangeType: "", EventKey: "xxx" }
客服消息 -------------------------------------
客服消息 Token: xxx OpenKfID: xxx
客服消息 获取body err: invalid character '<' looking for beginning of value
incoming message: RxMessage { FromUserID: "", SendTime: 1711176921000000000, MsgType: "event", MsgID: 0, AgentID: 0, Event: "kf_msg_or_event", ChangeType: "", EventKey: "xxx" }
客服消息 -------------------------------------
客服消息 Token: xxx OpenKfID: xxx
客服消息 获取body err: invalid character '<' looking for beginning of value

**Comment by whyiyhw** [comment]
这边无法复现，什么场景下会出现呢？

**Comment by hyzaw** [comment]
> 这边无法复现，什么场景下会出现呢？

修改源码指定微信host会出现，不知道是不是我改的不对

**Comment by whyiyhw** [comment]
emmmm 那你看下我最新的提交，已经支持了自定义企业微信 host

**Comment by hyzaw** [comment]
> emmmm 那你看下我最新的提交，已经支持了自定义企业微信 host

刚看了眼你那个好像只改了一半 提了个pr

**Comment by whyiyhw** [comment]
已 merge
