### ISSUE TITLE
请求的资源不存在

### ISSUE THREAD

**Issue by renwofei423** [whyiyhw/chatgpt-wechat#13]
部署好后，发信息，没有任何回应，看容器错误：
{"@timestamp":"2023-03-18T16:50:24.936+08:00","caller":"response/response.go:42","content":"【API-ERR】 : ErrCode:404，ErrMsg:请求资源不存在\n接口不存在\nmain.(*NotFoundHandler).ServeHTTP\n\t/build/service/chat/api/chat.go:54\ngithub.com/zeromicro/go-zero/rest/handler.LogHandler.func1\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/loghandler.go:47\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/zeromicro/go-zero/rest/handler.TraceHandler.func1.1\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/tracehandler.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/zeromicro/go-zero/rest.(*engine).notFoundHandler.func1\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/engine.go:221\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/zeromicro/go-zero/rest/router.(*patRouter).handleNotFound\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/router/patrouter.go:95\ngithub.com/zeromicro/go-zero/rest/router.(*patRouter).ServeHTTP\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/router/patrouter.go:73\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594 ","level":"error","span":"d5dce3b66da0f389","trace":"4b6096f8b4c2f401523bf8f385a1c7fd"}

到底是微信没连上，还是GPT没连上？

**Comment by whyiyhw** [comment]
确认下容器内端口8888是否更改

**Comment by whyiyhw** [comment]
第二个就是确认你企业微信上配置的是8888还是8887端口，使用服务器直连的，需要使用8887端口

**Comment by renwofei423** [comment]
> 第二个就是确认你企业微信上配置的是8888还是8887端口，使用服务器直连的，需要使用8887端口

看样子应该是这个原因。

我改成了服务器直连，设置了8887端口就好使了，感谢！

**Comment by renwofei423** [comment]
另外请问一下，现在只能直接**单独提问**，能实现编程聊天机器人，在群里@它 就可以回复吗？
