### ISSUE TITLE
请问代码里面的数据库是用来做什么的？

### ISSUE THREAD

**Issue by nagaki09** [whyiyhw/chatgpt-wechat#15]
替换成自己的需要做哪些处理呢

**Comment by whyiyhw** [comment]
数据库，主要作用就是，一些配置与上下文记录控制用。
替换成自己的，
- 需要去掉docker-compose 的MySQL 模块，
- 自行建库通过 build init 里面的sql 去建表，
- 修改 yaml 里面的 db 链接配置就行
