### ISSUE TITLE
使用内网穿透把这个应用部署到内网的，可信IP该怎么配置

### ISSUE THREAD

**Issue by koala9527** [whyiyhw/chatgpt-wechat#17]
直接填写frp穿透出去的有公网IP的机器的IP地址无法使用，我使用内网机器 curl cip.cc  获取到的IP 地址填入可信IP 才能使用，但是这是家庭宽带，动态的IP ,该怎么解决

**Comment by whyiyhw** [comment]
两个思路
第一个：frp 是把公网请求拉到了你的内网，你出去的时候走的是本地的ip ，所以需要你在公网IP机器上，搭建一个代理服务，把本地发给企业微信的消息，通过服务器转发（考虑改 host 实现）。
第二个动态IP 是否存在范围或者规律，尽可能的去匹配

**Comment by koala9527** [comment]
知道了，应该是回调是直接通过内网机器直接发送给微信服务器的。需要加个代理。
