### ISSUE TITLE
为什么我用的是3.0的模型

### ISSUE THREAD

**Issue by valiner** [whyiyhw/chatgpt-wechat#18]
![image](https://user-images.githubusercontent.com/17878390/228753146-686e8bf6-7431-4a41-9fbf-7bf2cd024045.png)

**Comment by whyiyhw** [comment]
gpt4 是申请制的，如果你的账号有 gpt4 的权限，那么修改   `Model: "gpt-4"`  或者 通过 `#config_model:gpt-4` 来实时修改
