### ISSUE TITLE
大家有办法添加企业微信可信域名，个人添加企业微信可信IP？

### ISSUE THREAD

**Issue by Rwindest168888** [whyiyhw/chatgpt-wechat#2]
网上找了好多方法，现加不了可信任业微信可信域名，和IP，有办法的大佬，说一下，谢谢

**Comment by whyiyhw** [comment]
这个部分我文档已经更新，你可以通过 阿里云云函数>服务>函数>触发器管理（url）拿到公网可用 url
比如 `https://robot-xxxxxxxxxxxxx.cn-hangzhou.fcapp.run`

**Comment by explorerezral** [comment]
填域名那里提示“该域名主体为第三方服务商，请使用企业主体域名”

**Comment by whyiyhw** [comment]
我晚上开一个新的应用试试，实际上，我测试了阿里云跟 aircode 这家香港的服务商，都没有出现这个提示，会不会是已认证企业，绑定了域名导致出现这个提示，我晚上再试试，腾讯云跟 其他公司的函数云服务

**Comment by explorerezral** [comment]
我这边企业未认证呀，使用的阿里云函数计算，填公网url会报错

**Comment by shisaq** [comment]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/16144551/221141624-1c2d2559-0225-457a-9f45-75e733a01562.png">

**Comment by whyiyhw** [comment]
我的企业微信应用很早就申请了，那个时候估计都没问题。
- 不过我找到迂回绕过这个验证的办法了，  首先需要把阿里云云函数买到非大陆区域（香港，日本都行），需要自己购买一个域名，比如说 我有一个 xx.cn 的域名，然后在阿里云 fc-高级功能-域名管理中 添加自定义域名，下面会有一个cname ，去购买域名的服务商那里，把 cname 值 进行解析，这样就能用，未备案的域名通过 企业微信的验证😀

**Comment by Migflyway** [comment]
不太行啊

**Comment by whyiyhw** [comment]
> 不太行啊

有具体的步骤吗，我可能写的不太详细，但是思路上通过大陆外区域的云函数来绕开企业微信的域名检测机制是可行的，我开了一个新的应用测试是通过的

**Comment by shisaq** [comment]
已经用香港服务器和自定义域名成功绕过备案，谢谢

本来还卡在后端不知如何配置上，结果发现您又更新了详细步骤，给力
