### ISSUE TITLE
微信客服docker log显示access_token missing

### ISSUE THREAD

**Issue by Lumos-Obliviate** [whyiyhw/chatgpt-wechat#24]
按照正文内容顺利完成了企微机器人的配置，能够正常得到回复。
尝试改为配置到微信客服后台时，按照类似的方式在chat-api.yaml文档中填入微信客服后台的secret key、token、encodingAESkey，调用测试也通过，但发送消息时收不到回复，查看docker logs如下图，请问是否缺少了什么配置？
![屏幕截图 2023-04-03 173633](https://user-images.githubusercontent.com/57974734/229471692-b2f25e53-f0d1-4248-9899-df12efd77ae2.png)

**Comment by whyiyhw** [comment]
请确认下 CustomerServiceSecret 这个参数 有没有获取，这个跟 DefaultAgentSecret  是两个不同的参数
需要单独获取
