### ISSUE TITLE
请问在chat-web容器中出现Request Timeout错误，是什么意思？

### ISSUE THREAD

**Issue by fjliss** [whyiyhw/chatgpt-wechat#25]
如题，go语言已经安装了，可以接收企业微信的信息，但是，openai没法应答

**Comment by fjliss** [comment]
非常感谢你的答疑

**Comment by whyiyhw** [comment]
这种情况你需要确认下
1. 你服务器所在的环境能否直接访问 api.openai.com
2. 如果是通过代理的方式访问的，需要确认 配置文件的代理 ip:port. 是否正确
