### ISSUE TITLE
企业微信Openapi回调失败是什么原因呢

### ISSUE THREAD

**Issue by KTechRick** [whyiyhw/chatgpt-wechat#26]
返回
{"code":404,"msg":"请求资源不存在","data":{}}

日志
{"@timestamp":"2023-04-04T15:44:12.794+08:00","caller":"accesslog/accesslog.go:28","content":"","level":"info","request":{"url":"/","method":"GET","query":"echostr=0kxsfwgukCLx0uMLB1Aw8MMtRX%2BFHYoSD9pYtF7uNiJlTh5TA0sYs7R2B2CcCVBHcgTl6%2Bup%2Brch3vrz2Br2hw%3D%3D\u0026msg_signature=fdc1308eb78f94ae5e9da5f1026c9c50b291f6d8\u0026nonce=1679821968\u0026timestamp=1680594252","body":"","header":{"Accept":["*/*"],"Cache-Control":["no-cache"],"Pragma":["no-cache"],"User-Agent":["Mozilla/4.0"]},"const":-1},"span":"e899a2cc31ff24de","trace":"31090e22c3e4176a40f302cadb01742b"}
{"@timestamp":"2023-04-04T15:44:12.794+08:00","caller":"response/response.go:42","content":"【API-ERR】 : ErrCode:404，ErrMsg:请求资源不存在\n接口不存在\nmain.(*NotFoundHandler).ServeHTTP\n\t/build/service/chat/api/chat.go:75\ngithub.com/zeromicro/go-zero/rest/handler.LogHandler.func1\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/loghandler.go:47\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/zeromicro/go-zero/rest/handler.TraceHandler.func1.1\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/tracehandler.go:64\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/zeromicro/go-zero/rest.(*engine).notFoundHandler.func1\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/engine.go:221\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/zeromicro/go-zero/rest/router.(*patRouter).handleNotFound\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/router/patrouter.go:95\ngithub.com/zeromicro/go-zero/rest/router.(*patRouter).ServeHTTP\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/router/patrouter.go:73\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594 ","level":"error","span":"e899a2cc31ff24de","trace":"31090e22c3e4176a40f302cadb01742b"}
{"@timestamp":"2023-04-04T15:44:12.794+08:00","caller":"response/response.go:63","content":"","level":"info","response":{"code":404,"msg":"请求资源不存在","data":{}},"span":"e899a2cc31ff24de","trace":"31090e22c3e4176a40f302cadb01742b"}
{"@timestamp":"2023-04-04T15:44:12.794+08:00","caller":"handler/loghandler.go:160","content":"[HTTP] 200 - GET /?msg_signature=fdc1308eb78f94ae5e9da5f1026c9c50b291f6d8\u0026timestamp=1680594252\u0026nonce=1679821968\u0026echostr=0kxsfwgukCLx0uMLB1Aw8MMtRX%2BFHYoSD9pYtF7uNiJlTh5TA0sYs7R2B2CcCVBHcgTl6%2Bup%2Brch3vrz2Br2hw%3D%3D - 175.27.32.31:26172 - Mozilla/4.0","duration":"0.2ms","level":"info","span":"e899a2cc31ff24de","trace":"31090e22c3e4176a40f302cadb01742b"}

**Comment by zhuzf88** [comment]
我也是回调地址请求不通过

**Comment by whyiyhw** [comment]
端口确认下哦，目前 8887 端口是用于与企业微信交互，8888 是真实的业务逻辑服务端口
具体 可查看 chat-api.yaml.complete.bak
