### ISSUE TITLE
想咨询一下微信客服功能的使用

### ISSUE THREAD

**Issue by nagaki09** [whyiyhw/chatgpt-wechat#29]
感谢作者，已经能跑通基本的企业微信内容应用和chatgpt的对接
但是仔细翻看了本项目的说明文档后，还是不清楚”（视频号/公众号/小程序/微信/企微/app/web）支持多渠道客服消息接入”
的具体配置流程
希望能简单说明一下操作步骤？
微信客服也有api，创建的客服也有对应的配置，项目这侧看到
![image](https://user-images.githubusercontent.com/31009189/229799971-60bcc12a-8c8b-4e29-82f7-6e251606f223.png)
不太清楚每个地方具体怎么对接

**Comment by whyiyhw** [comment]
https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/custom_support_service.md

基础文档已经补充了，后续会补全每种接入方式，不过我感觉这块确实是可以先看看企业微信的文档

**Comment by nagaki09** [comment]
> https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/custom_support_service.md
> 
> 基础文档已经补充了，后续会补全每种接入方式，不过我感觉这块确实是可以先看看企业微信的文档

感谢~我马上试试
