### ISSUE TITLE
build的问题提问

### ISSUE THREAD

**Issue by jshen0754** [whyiyhw/chatgpt-wechat#32]
1，修改了app Secret或者token，EncodingAESKey以后，是否需要重新build？
2，build的时候提示 Service 'web' failed to build : Build failed ，是什么问题？

**Comment by whyiyhw** [comment]
1. 是的，修改后需要重新build 
2. 能否提供更加详细的失败说明，这个信息，我只知道 build 失败了，不知道为什么失败

**Comment by jshen0754** [comment]
关键就是只提示Service 'web' failed to build : Build failed，没有其他附加信息，不知道问题出在哪。
请问在哪可以看build详细报错？

**Comment by whyiyhw** [comment]
一般都会有 `Service 'web' failed to build: The command '/bin/sh -c sh /app/docker/prepare.sh' returned a non-zero code: 2`
类似于后面的错误信息,表明是在哪一步build 失败，
目前这个build 出问题最大的可能性，在于 ` RUN  apk add tzdata` 拉取第三方包的时候异常
你如果熟悉 docker 可以改改 Dockerfile 单独 build 试试
