### ISSUE TITLE
现在微信封号严重，就问这个方法会被封号么？

### ISSUE THREAD

**Issue by solofang** [whyiyhw/chatgpt-wechat#33]
现在微信封号严重，就问这个方法会被封号么？

**Comment by whyiyhw** [comment]
这一个多月来，没有用户跟我反馈有封号的情况，项目完全走企业微信的官方api , 不存在 hook 微信跟企业微信的情况，所以我以为安全性上还是有保证的。
项目缺点就是，目前不适用于群聊场景，你们有这个需求的，最好开小号用其他项目。

**Comment by jshen0754** [comment]
企业微信本来就支持第三方接入，所以理论上是不会被封的，不过建议还是再加上一些敏感词过滤，你懂的。
