### ISSUE TITLE
上下文需要怎么处理？

### ISSUE THREAD

**Issue by Meayair** [whyiyhw/chatgpt-wechat#34]
上下文需要怎么处理？
系统错误:error, This model's maximum context length is 4097 tokens. However, you requested 4459 tokens (2459 in the messages, 2000 in the completion). Please reduce the length of the messages or completion.

**Comment by whyiyhw** [comment]
是否使用了最新版本？

发送 #clear 清理即可

**Comment by Meayair** [comment]
取的最新代码，#clear这个看到了，“自适应的上下文长度，不用再频繁手动清理上下文环境 2023-04-09”，我以为这个说的是可以自动清理

**Comment by whyiyhw** [comment]
最新的意思是 ，昨天晚上 11点，我更新的代码。如果 summery 机制在正常工作，那应该不会出现这个限制，你是对话了多少轮触发的？
还有一个关于这个机制的补丁正在写，到时候这个机制就完善了

**Comment by Meayair** [comment]
懂了，感谢~

**Comment by whyiyhw** [comment]
最新代码已经通过精细化token计算，跟发消息前的主动遗忘，解决了这个问题。
