### ISSUE TITLE
AI要经过二三十秒才会回答，这个速度正常么？

### ISSUE THREAD

**Issue by 5700pgf** [whyiyhw/chatgpt-wechat#35]
想了解下从问问题到AI回答这个时间多长是正常的，我试了阿里的香港VPS和甲骨文的美国VPS，从我提问到AI回答，这中间都要经过二三十秒的时间，这个时间正常么？或是有什么方法可以缩短这个时间？

**Comment by whyiyhw** [comment]
使用免费账户的API，在高峰期确实会这样，
1. 账户绑卡后试试？
2. 目前正在考虑做 llm 的抽象，一旦国内的大模型API 可用，可以切回国内，这样响应时间会比较短
目前正常的初次响应时间 在 3-5S  内，免费账户在openai 高峰 10 - 30s 不等, 还会有 过载被拒绝的可能
