### ISSUE TITLE
发送消息后返回：系统错误

### ISSUE THREAD

**Issue by deemoartisan** [whyiyhw/chatgpt-wechat#37]
系统错误:error, You exceeded your current quota, please check your plan and billing details.
到网站上看了下还是可以正常对话的，通过应用就不行了，请问这个是啥情况呀

**Comment by whyiyhw** [comment]
它已经告诉你了，超出限额了。
你要不要去 openai 的管理页面看看，应该是额度用完了，
或者赠送的金额有效期只有3个月，是不是过期了。
再申请个账号或者绑卡~

**Comment by whyiyhw** [comment]
更换 key 后 是否 重新进行了构建 `docker-compose build  && docker-compose up -d` ?
