### ISSUE TITLE
AgentId 好像没用上阿：创建一个企业微信内部应用，并获取到 AgentId 和 Secret

### ISSUE THREAD

**Issue by ntgeralt** [whyiyhw/chatgpt-wechat#39]
我看教程开头提示需要记下AgentId 
然而yaml没有需要填写AgentId 的地方

然后  DefaultAgentSecret: "55sO-xxxxxxxxxxxxxxxxxxU"   

那些xxx最后有个U

**Comment by whyiyhw** [comment]
多应用的时候有用，你可以看下完整版本的配置文件，单应用时不用填

default 这个是示例，你填你自己的就好
