### ISSUE TITLE
系统过载请稍后再试

### ISSUE THREAD

**Issue by Doject** [whyiyhw/chatgpt-wechat#4]
就一个用户 一直提示 系统过载请稍后再试
其他用户是正常的，回答也正常

**Comment by whyiyhw** [comment]
这个暂时不好排查，我还没有对openai 的错误进行详细的分类，目前统一是系统过载，你可以看下 docker 容器的 log，这个周末我再完善下

**Comment by whyiyhw** [comment]
目前已经完善了error log，可以升级到0.3 以后自行排查~
