### ISSUE TITLE
每个问题的回答需要等30s左右，是正常的吗?

### ISSUE THREAD

**Issue by Alex-coffen** [whyiyhw/chatgpt-wechat#40]
![image](https://user-images.githubusercontent.com/55936323/231926536-f740e2fb-2797-4ad0-b163-b3c5f85e6370.png)

基本上每条信息在微信上都需要等20~30s，还可以优化么？

**Comment by whyiyhw** [comment]
请更新至最新版本， 目前已经进行 stream 分段响应

**Comment by Alex-coffen** [comment]
> 请更新至最新版本， 目前已经进行 stream 分段响应

谢谢。
是git pull之后重新做下面吗？

# 修改好后生成集成应用镜像
sudo docker-compose build

# 启动集成应用
sudo docker-compose up -d

**Comment by whyiyhw** [comment]
是的

**Comment by Alex-coffen** [comment]
非常感谢！非常好的应用！谢谢分享~
