### ISSUE TITLE
请问要如何清除前面的上下文，开启一个新的对话？

### ISSUE THREAD

**Issue by 5700pgf** [whyiyhw/chatgpt-wechat#41]
想知道使用客服功能如何清除前面的上下文，开启一个新的对话，我给机器人发错了一个东西，看提示是回答超出了4K的限制，然后就没法用了，一直报错，看了DOCKER日志，发现是后面的对话会把前面的问题也带进去，导致那个会出错的问题也一直被提交。

**Comment by Alex-coffen** [comment]
对话输入：#clear

**Comment by 5700pgf** [comment]
感谢你的回复~
