### ISSUE TITLE
图片识别？

### ISSUE THREAD

**Issue by Alex-coffen** [whyiyhw/chatgpt-wechat#42]
![Screenshot_2023-04-17-10-32-23-83_e39d2c7de19156b0683cd93e8735f348](https://user-images.githubusercontent.com/55936323/232364221-5bf9add4-7556-4ca4-bf47-11ffbbdd4006.jpg)
阿里的图片识别效果感人啊！！

**Comment by whyiyhw** [comment]
emmm 目前通用的图片识别场景，还没有好的方案，我这个只能用于 笔试，答题的场景（文字识别）。
后续会考虑多支持几个场景

**Comment by Alex-coffen** [comment]
哦哦好的
