### ISSUE TITLE
 应用消息-发送失败 err:Post

### ISSUE THREAD

**Issue by LMY425** [whyiyhw/chatgpt-wechat#47]
大佬，提示这个是哪方面的问题，该如何解决？   应用消息-发送失败 err:Post \"https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=\": dial tcp: lookup qyapi.weixin.qq.com on 127.0.0.11:53: read udp 127.0.0.1:36654-\u003e127.0.0.11:53: i/o timeout","level":"error"}

**Comment by whyiyhw** [comment]
从报错来看，是 dns 解析没有成功导致的，你在本地去ping 这个域名 `qyapi.weixin.qq.com` ，能否成功？

**Comment by LMY425** [comment]
ping了，可以通

**Comment by liuchangshui** [comment]
系统错误:error, You exceeded your current quota, please check your plan and billing details.
给机器人发送信息，收到如下信息，大家有遇到的嘛？
