### ISSUE TITLE
系统错误:error, You exceeded your current quota, please check your plan and billing details. 

### ISSUE THREAD

**Issue by liuchangshui** [whyiyhw/chatgpt-wechat#49]
系统错误:error, You exceeded your current quota, please check your plan and billing details. 
给机器人发送信息，收到如下信息，大家有遇到的嘛？

**Comment by whyiyhw** [comment]
#37 参考下这个 issues ， 换一个key 重新 build 再 up（最新版本可以 docker-compose restart web）

**Comment by liuchangshui** [comment]
感谢回答，我重新生成的key，然后重新做的build和up，目前的情况是，一执行就时效，去openapi的管理台上看，新生成的key的过期日期由 never变成了今天

**Comment by whyiyhw** [comment]
[https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details](https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details)
参考官方的 FQA ，应该就是当前账号的免费余额用完了。建议换个账号或者绑卡
你可以通过 [https://platform.openai.com/account/usage](https://platform.openai.com/account/usage) 查看使用额度
