### ISSUE TITLE
关于企业微信的配置Authsecret和AuthExpire哪里获取呀

### ISSUE THREAD

**Issue by Angusvencent** [whyiyhw/chatgpt-wechat#5]
关于企业微信的配置Authsecret和AuthExpire哪里获取呀

**Comment by whyiyhw** [comment]
如果指的是 Auth 下的 AccessSecret 跟 AccessExpire ，这个是你自己填的，建议AccessSecret 随机生成，AccessExpire 如果不想维护可以填的时间长一些~

**Comment by Angusvencent** [comment]
不好意思，我才发现我弄错了
![image](https://user-images.githubusercontent.com/115913884/222918999-b019ad4c-7842-4257-8dcc-de49cd6336e8.png)
这两个不需要改，但是我把它改了，现在改回去之后需要进行哪些操作，我刚刚填错了已经部署完成了，这会debug发现是这个地方弄错了。请问我除了改回去还要进行哪些操作？
