### ISSUE TITLE
chat-api.yaml启动会提示 Draw is not set

### ISSUE THREAD

**Issue by tee09** [whyiyhw/chatgpt-wechat#52]
如果不设置draw参数，chat_web的容器拉不起来。
改完之后又碰到了编码的问题，
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 55 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 14 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 8 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 16 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 51 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 27 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 36 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 54 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 11 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 11 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 39 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 47 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 8 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 25 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 13 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 32 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 12 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 6 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1
Starting server at 0.0.0.0:8888...
panic: illegal base64 data at input byte 44

goroutine 41 [running]:
chat/common/wecom.XmlServe()
        /build/common/wecom/wecom.go:254 +0x394
created by main.main
        /build/service/chat/api/chat.go:64 +0x4b1

**Comment by whyiyhw** [comment]
不好意思，昨天新加的功能忘记设置可选了🧎，你拉下最新的代码。

`panic: illegal base64 data at input byte 44 `， 这个就很明显了, 检查下 你的 Token 跟 EncodingAESKey

**Comment by tee09** [comment]
> 不好意思，昨天新加的功能忘记设置可选了🧎，你拉下最新的代码。
> 
> `panic: illegal base64 data at input byte 44 `， 这个就很明显了, 检查下 你的 Token 跟 EncodingAESKey

👌  搞定了

**Comment by tee09** [comment]
openai回调地址请求不通过。端口是可以访问到的，服务器也已经设置好代理可以出去。还有那些那些可能性会导致这个问题？

**Comment by whyiyhw** [comment]
企微回调认证未通过，企微服务器 --> host:ip  
这一步错误 90% 的都是自己改了 8887 端口映射 ，然后配置错了，另外的就是服务器网络安全策略没开放端口
其他的就是 Token 跟 EncodingAESKey 填错了

**Comment by tee09** [comment]
> 企微回调认证未通过，企微服务器 --> host:ip 这一步错误 90% 的都是自己改了 8887 端口映射 ，然后配置错了，另外的就是服务器网络安全策略没开放端口 其他的就是 Token 跟 EncodingAESKey 填错了

再三确认过了，策略都是开的，端口也可以打开。测试过了服务器端没有抓到包，应该是这个段IP被注册过了，直接没有发请求出来。

**Comment by tee09** [comment]
换了一个企业微信，设置了可信，现在提示回调URL校验失败，在服务器上抓包发现HTTP请求的时候只是GET /没有带请求。服务器回的400 bad request。

**Comment by whyiyhw** [comment]
企业微信 验证过来的 请求，都是 xml 类型的请求 具体逻辑可以看这段js, 其他语言类似
<img width="620" alt="image" src="https://user-images.githubusercontent.com/31464280/234828080-c4757bf9-3070-470f-b557-bcdcf3b8349a.png">
还是 那个问题 8887 端口 ，修改配置文件后是否 (build and up / restart web )?

**Comment by tee09** [comment]
> 如果请求没发出来，那可能是ip被ban了，那可以试试云函数+cname 的方式绕过去，转发到服务器

验证通过了，但是没有回消息，我怎么验证我的服务器可以调通openai呢？

**Comment by whyiyhw** [comment]
直接 curl 看看能请求到 openai，如果能
就看 docker-compose logs web 有没有响应信息

**Comment by whyiyhw** [comment]
access_token 生成错误，你检查下  
 CorpID: "wwxxxxxxxxxxxxxxxxxxxx"                         # 企业微信 CorpID  
DefaultAgentSecret: "55sO-xxxxxxxxxxxxxxxxxx"     # 企业微信应用 Secret  
这两个参数是否设置正常，还有改完记得 restart web

**Comment by tee09** [comment]
> access_token 生成错误，你检查下 CorpID: "wwxxxxxxxxxxxxxxxxxxxx" # 企业微信 CorpID DefaultAgentSecret: "55sO-xxxxxxxxxxxxxxxxxx" # 企业微信应用 Secret 这两个参数是否设置正常，还有改完记得 restart web

已经解决了，还是网络问题，全局代理把请求不知道丢哪里去了。

**Comment by whyiyhw** [comment]
用了感觉还不错的话，可以考虑给个 🌟

**Comment by tee09** [comment]
> 用了感觉还不错的话，可以考虑给个 🌟

必须的，已经小范围推广给其他朋友了。

**Comment by whyiyhw** [comment]
十分感谢🙏  😊
