### ISSUE TITLE
一个优化的 Dockerfile

### ISSUE THREAD

**Issue by laalaguer** [whyiyhw/chatgpt-wechat#54]
针对 海外VPS

https://github.com/whyiyhw/chatgpt-wechat/blob/main/chat/Dockerfile

Dockerfile 中 `GOPROXY=https://goproxy.cn,direct` 和 `sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories` 可以去掉？ 刚试了一下，海外VPS去掉后下载速度飞起。

**Comment by whyiyhw** [comment]
感谢提出，我尝试改下，根据网络环境做下区分
