### ISSUE TITLE
ChatStream 的 Model 没有使用 config 的配置

### ISSUE THREAD

**Issue by danachy** [whyiyhw/chatgpt-wechat#57]
[chat.go](https://github.com/whyiyhw/chatgpt-wechat/blob/main/chat/common/openai/chat.go)

`request := copenai.ChatCompletionRequest{
		Model:       ChatModel,
		Messages:    messages,
		MaxTokens:   c.MaxToken,
		Temperature: c.Temperature,
		TopP:        1,
	}
`

看起来是这里导致 Model 一直使用 gpt-3.5-turbo。

**Comment by whyiyhw** [comment]
感谢🙏，已修复
