### ISSUE TITLE
调用 stable diffusion 作图 能力报错

### ISSUE THREAD

**Issue by taoxiaojin** [whyiyhw/chatgpt-wechat#58]
报错如下：

`incoming message: RxMessage { FromUserID: "10004", SendTime: 1683369342000000000, MsgType: "text", MsgID: 7230016272080145700, AgentID: 1000080, Event: "", ChangeType: "", Content: "#draw:a cute cat" }
{"@timestamp":"2023-05-06T18:35:42.492+08:00","caller":"sqlx/stmt.go:132","content":"sql query: SELECT `id`,`user`,`agent_id`,`model`,`prompt`,`created_at`,`updated_at` FROM `chat_config` WHERE user = '10004' AND agent_id = 1000080 ORDER BY id desc","duration":"1.8ms","level":"info","span":"e26b3ed7917ff038","trace":"efe5218a8462c976b2ddd93306875bbf"}
{"@timestamp":"2023-05-06T18:35:42.492+08:00","caller":"logic/chatlogic.go:749","content":"draw request client build success","level":"info"}
{"@timestamp":"2023-05-06T18:35:42.516+08:00","caller":"internal/log.go:57","content":"(/api/msg/push - 127.0.0.1:49472) interface conversion: interface {} is nil, not []interface {}\ngoroutine 232 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1.1()\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/recoverhandler.go:16 +0x66\npanic({0xf039a0, 0xc000a29d70})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\nchat/service/chat/api/internal/logic.CommendDraw.exec({}, 0xc0004220e0, 0xc000036400)\n\t/build/service/chat/api/internal/logic/chatlogic.go:779 +0x114a\nchat/service/chat/api/internal/logic.(*ChatLogic).FactoryCommend(0xc0002a2450?, 0xc000036400)\n\t/build/service/chat/api/internal/logic/chatlogic.go:358 +0x56d\nchat/service/chat/api/internal/logic.(*ChatLogic).Chat(0xc0004220e0, 0xc000036400)\n\t/build/service/chat/api/internal/logic/chatlogic.go:71 +0x689\nchat/service/chat/api/internal/handler.ChatHandler.func1({0x150e568, 0xc0002fe9c0}, 0xc000c10500)\n\t/build/service/chat/api/internal/handler/chathandler.go:35 +0x21f\nchat/service/chat/api/internal/middleware.(*AccessLogMiddleware).Handle.func1({0x150e568, 0xc0002fe9c0}, 0xc000c10500)\n\t/build/service/chat/api/internal/middleware/accesslogmiddleware.go:30 +0x225\nnet/http.HandlerFunc.ServeHTTP(0xc0009a1cc0?, {0x150e568?, 0xc0002fe9c0?}, 0xc000936180?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.Authorize.func1.1({0x150e568, 0xc0002fe9c0}, 0xc000c10400)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/authhandler.go:81 +0x4b3\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x150e568?, 0xc0002fe9c0?}, 0x1c67920?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.GunzipHandler.func1({0x150e568, 0xc0002fe9c0}, 0xc000c10400)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/gunziphandler.go:26 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xedbe8247e?, {0x150e568?, 0xc0002fe9c0?}, 0x102a5cfa845?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MaxBytesHandler.func2.1({0x150e568?, 0xc0002fe9c0?}, 0x1c67920?)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/maxbyteshandler.go:24 +0xff\nnet/http.HandlerFunc.ServeHTTP(0x45d964b800?, {0x150e568?, 0xc0002fe9c0?}, 0x0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MetricHandler.func1.1({0x150e568, 0xc0002fe9c0}, 0x30020000666f?)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/metrichandler.go:21 +0xd5\nnet/http.HandlerFunc.ServeHTTP(0x5e9400005546?, {0x150e568?, 0xc0002fe9c0?}, 0xc000b6a320?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1({0x150e568?, 0xc0002fe9c0?}, 0x0?)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/recoverhandler.go:21 +0x83\nnet/http.HandlerFunc.ServeHTTP(0x5c55000053d1?, {0x150e568?, 0xc0002fe9c0?}, 0x764aa6?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP.func1()\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/timeouthandler.go:79 +0x7c\ncreated by github.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.4.4/rest/handler/timeouthandler.go:73 +0x350\n","level":"error","span":"6bb35de8a13ee3b9","trace":"829e5f522500aee554b6d687aa7f004b"}
{"@timestamp":"2023-05-06T18:35:42.516+08:00","caller":"handler/loghandler.go:162","content":"[HTTP] 500 - POST /api/msg/push - 127.0.0.1:49472 - Go-http-client/1.1\nPOST /api/msg/push HTTP/1.1\r\nHost: localhost:8888\r\nAccept-Encoding: gzip\r\nAuthorization: Bearer elcklkIjoxfQ.01Ksjy_VlASlDJbANLV7SaA_NA0\r\nContent-Length: 82\r\nContent-Type: application/json\r\nUser-Agent: Go-http-client/1.1\r\n\r\n{\"channel\":\"openai\",\"msg\":\"#draw:a cute cat\",\"user_id\":\"10004\",\"agent_id\":1000080}","duration":"26.0ms","level":"error","span":"6bb35de8a13ee3b9","trace":"829e5f522500aee554b6d687aa7f004b"}`

**Comment by taoxiaojin** [comment]
host 写的有问题，多加了：sdapi/v1/txt2img

**Comment by Sun-Jingjun** [comment]
请教下这个作图如何配置，我看作者没有相关的文档
