### ISSUE TITLE
使用#draw时能否去掉500字符限制

### ISSUE THREAD

**Issue by DarknessMaria** [whyiyhw/chatgpt-wechat#62]
用SD绘画的话 参数很容易超过500字符，能否去掉

**Comment by whyiyhw** [comment]
确实是会有这个问题，我这两天晚上有空了处理下。
另外我更新了，本地服务远程调用的文档，你本地电脑配置 ok 的话，可以试试这个方案

https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/draw.md

**Comment by DarknessMaria** [comment]
能不能直接把字符限制数写进配置文件，我直接修改wecom.go里面的字数或者修改成1000都无效
修改后使用#draw超过500也不行
GPT4能支持到8,192 tokens和32,768 tokens，万一有大佬有API哪（doge）

**Comment by whyiyhw** [comment]
> 能不能直接把字符限制数写进配置文件，我直接修改wecom.go里面的字数或者修改成1000都无效 修改后使用#draw超过500也不行 GPT4能支持到8,192 tokens和32,768 tokens，万一有大佬有API哪（doge）

已经支持 max token 通过配置自行调整
