### ISSUE TITLE
使用Stable Diffusion时附加的参数

### ISSUE THREAD

**Issue by DarknessMaria** [whyiyhw/chatgpt-wechat#63]
目前好像只支持prompt但是SD包含许多参数项如：
shukezouma, octane render, hdr, (hyperdetailed:1.15), (soft light, sharp:1.2), 1girl, beautiful girl, ultra detailed eyes, mature, plump, thick, rainbow painting drops, paint teardrops, woman made up from paint, entirely paint, splat, splash, long colored hair, kimono made from paint, ultra detailed texture kimono, rainbow paint kimono, paint bulb, paint drops, (hair ornaments, earrings, flowers hair ornaments, butterflies hair ornaments), outdoors, sakura trees
**Negative prompt:** 3d, cartoon, anime, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, bad anatomy, girl, loli, young, large breasts, red eyes, muscular, over saturated, over saturated, over saturated
**Steps:** 35, **Sampler:** DPM++ 2M Karras, CFG **scale:** 7, **Seed:** 4146499890, **Size:** 512x768, **Model hash:** ec6f68ea63, **Model:** lyriel_v16, **Denoising strength:** 0.52, **ENSD:** 31337, **Hires resize:** 832x1280, **Hires steps:** 40, **Hires upscaler:** Latent
这些反向词甚至算法，使用模组，图像大小等参数能否支持传入？

**Comment by whyiyhw** [comment]
参数倒是能加进去，不过这个功能就跟一般人无缘了，我在考虑怎么加，比较合适，毕竟你只有一个微信输入框，这些参数你还需要在额外的地方进行编辑设置
有什么好的建议没有呢？

**Comment by DarknessMaria** [comment]
新增个指令比如#draw2:用[]{}<>之类的包裹参数名与值然后直接整个作为一个map传给API？

**Comment by whyiyhw** [comment]
考虑了下，
单行则为默认参数，
多行直接支持了 从 C 站 copy 的参数，你可以 pull 再重新 build 看看效果。

**Comment by DarknessMaria** [comment]
添加了Steps：参数后 画不出图

**Comment by whyiyhw** [comment]
> 目前好像只支持prompt但是SD包含许多参数项如： shukezouma, octane render, hdr, (hyperdetailed:1.15), (soft light, sharp:1.2), 1girl, beautiful girl, ultra detailed eyes, mature, plump, thick, rainbow painting drops, paint teardrops, woman made up from paint, entirely paint, splat, splash, long colored hair, kimono made from paint, ultra detailed texture kimono, rainbow paint kimono, paint bulb, paint drops, (hair ornaments, earrings, flowers hair ornaments, butterflies hair ornaments), outdoors, sakura trees **Negative prompt:** 3d, cartoon, anime, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, bad anatomy, girl, loli, young, large breasts, red eyes, muscular, over saturated, over saturated, over saturated **Steps:** 35, **Sampler:** DPM++ 2M Karras, CFG **scale:** 7, **Seed:** 4146499890, **Size:** 512x768, **Model hash:** ec6f68ea63, **Model:** lyriel_v16, **Denoising strength:** 0.52, **ENSD:** 31337, **Hires resize:** 832x1280, **Hires steps:** 40, **Hires upscaler:** Latent 这些反向词甚至算法，使用模组，图像大小等参数能否支持传入？

emmmm ，一个是大小写问题，还有一个问题就是参数的对应关系，hr系列 目前还没找到合适的解释，我感觉还是参数没测全，晚上多测试几个 demo 看看能不能复现

**Comment by DarknessMaria** [comment]
> emmmm ，一个是大小写问题，还有一个问题就是参数的对应关系，hr系列 目前还没找到合适的解释，我感觉还是参数没测全，晚上多测试几个 demo 看看能不能复现

hr系列需要enable_hr:true 还需要设置放大算法比如HrUpscaler: "Latent"，另外根据官方的API，推测采样方法Sampler的键名应该是"sampler_index": "Euler",
![image](https://github.com/whyiyhw/chatgpt-wechat/assets/12655164/e0ec0157-ba39-44de-b699-c77cbb1dcf86)

我尝试在配置里写死小参只用prompt和negative prompt
![image](https://github.com/whyiyhw/chatgpt-wechat/assets/12655164/744092a7-c8fc-41e6-9756-171647a0be34)

在没有给出Steps:时候
![image](https://github.com/whyiyhw/chatgpt-wechat/assets/12655164/7f2a9750-349d-4d6e-85ef-b6a77deb762d)
可正常绘画，且HR系列参数生效

但是在给出Steps:参数后
![image](https://github.com/whyiyhw/chatgpt-wechat/assets/12655164/2c89ddc1-81ff-47c3-b4c7-4128dc68e192)
无法正常绘画，且查看SD后台发现带入的Steps:参数并未生效，但是生成的图片却是我配置写死HR系列参数

我的猜测是带入Steps:参数后的代码可能把prompt和negative prompt都覆盖了或者是带入参数后生成的数据格式有问题
