### ISSUE TITLE
能更新下插件部署的说明么？小白不太明白

### ISSUE THREAD

**Issue by Alex-coffen** [whyiyhw/chatgpt-wechat#64]

**Comment by whyiyhw** [comment]
你可以看下 完整配置
启动 还是 docker-compose up -d ，文档只能说等我加班没那么多的时候，肯定会补充😭

**Comment by Alex-coffen** [comment]
好的谢谢。
我想请问下，如果我的chatgpt-wechat整个项目本身就是放在国外的服务器上，那么draw不用远端转本地，所以配置是不是应该变成：

Draw:
  Enable: true
  StableDiffusion:
    Host: "**http://127.0.0.1:7860**"
    Auth:
      Username: ""
      Password: ""

服务器上SD服务的端口是不是7860？
用户名密码是否留空？

**Comment by DarknessMaria** [comment]
如果是本机同时搭建了SD服务且默认端口没变的情况下 填写Host: "http://127.0.0.1:7860/"就可以
如果是在另外台服务器搭建的SD服务就需要更换IP

**Comment by DarknessMaria** [comment]
> 好的谢谢。 我想请问下，如果我的chatgpt-wechat整个项目本身就是放在国外的服务器上，那么draw不用远端转本地，所以配置是不是应该变成：
> 
> Draw: Enable: true StableDiffusion: Host: "**http://127.0.0.1:7860**" Auth: Username: "" Password: ""
> 
> 服务器上SD服务的端口是不是7860？ 用户名密码是否留空？

如果是本机同时搭建了SD服务且默认端口没变的情况下 填写Host: "[http://127.0.0.1:7860/"就可以](http://127.0.0.1:7860/%22%E5%B0%B1%E5%8F%AF%E4%BB%A5)
如果是在另外台服务器搭建的SD服务就需要更换IP

**Comment by Alex-coffen** [comment]
谢谢。再请教一下，SD1.5得搭建有集成在我们这个项目么？还是需要自己去搭建SD？

**Comment by DarknessMaria** [comment]
> 谢谢。再请教一下，SD1.5得搭建有集成在我们这个项目么？还是需要自己去搭建SD？

需要自己搭建

**Comment by Alex-coffen** [comment]
是dockerhub还是有github的链接么？能提供一下吗？

**Comment by DarknessMaria** [comment]
> 是dockerhub还是有github的链接么？能提供一下吗？

https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by whyiyhw** [comment]
插件文档已更新，https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/plugin.md
