### ISSUE TITLE
可否支持多个企微客服？另，企微客服现在不支持插件是吗？

### ISSUE THREAD

**Issue by hai-luo** [whyiyhw/chatgpt-wechat#67]
希望可以支持多个企微客服，每个客服号可以对应不同的模型和baseprompt，现在好像只做了应用号的，baseprompt对客服无效。
也希望企微客服支持插件，禁用掉高危插件或者要求认证都可以。
感谢大佬

**Comment by whyiyhw** [comment]
这块我想做个 web 页面来进行管理，客服的一些配置需要 调用接口才能获取。
但是加班太厉害了，只能半夜有点时间做，做大的模块进度很慢。😭

**Comment by whyiyhw** [comment]
企微客服现在已经支持插件了

**Comment by whyiyhw** [comment]
插件文档已更新，https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/plugin.md

**Comment by whyiyhw** [comment]
web 网页端发布至对应的客服已完成，可通过 bot 设置，发布到对应的客服 
<img width="1358" alt="image" src="https://github.com/whyiyhw/chatgpt-wechat/assets/31464280/028b2722-902a-4393-9d6f-a765f597f783">
