### ISSUE TITLE
chatlogic.go 报错

### ISSUE THREAD

**Issue by mashihua** [whyiyhw/chatgpt-wechat#68]
https://github.com/whyiyhw/chatgpt-wechat/blob/main/chat/service/chat/api/internal/logic/chatlogic.go#L646

(/api/msg/push - 127.0.0.1:59590) runtime error: invalid memory address or nil pointer dereference\ngoroutine 10 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1.1()\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:16 +0x66\npanic({0x1028240, 0x1e87400})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\nchat/service/chat/api/internal/logic.CommendPromptSet.exec({}, 0xc0004608c0, 0xc0003e4d00)\n\t/build/service/chat/api/internal/logic/chatlogic.go:646 +0x151\nchat/service/chat/api/internal/logic.(*ChatLogic).FactoryCommend(0xc000301a70?, 0xc0003e4d00)\n\t/build/service/chat/api/internal/logic/chatlogic.go:358 +0x66d\nchat/service/chat/api/internal/logic.(*ChatLogic).Chat(0xc0004608c0, 0xc0003e4d00)\n\t/build/service/chat/api/internal/logic/chatlogic.go:68 +0x6c9\nchat/service/chat/api/internal/handler.ChatHandler.func1({0x1686590, 0xc0000b9ce0}, 0xc000496900)\n\t/build/service/chat/api/internal/handler/chathandler.go:35 +0x21f\nchat/service/chat/api/internal/middleware.(*AccessLogMiddleware).Handle.func1({0x1686590, 0xc0000b9ce0}, 0xc000496900)\n\t/build/service/chat/api/internal/middleware/accesslogmiddleware.go:30 +0x225\nnet/http.HandlerFunc.ServeHTTP(0xc00064fcc0?, {0x1686590?, 0xc0000b9ce0?}, 0xc0003a5b70?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.Authorize.func1.1({0x1686590, 0xc0000b9ce0}, 0xc000496800)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/authhandler.go:81 +0x4b3\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x1686590?, 0xc0000b9ce0?}, 0x0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.GunzipHandler.func1({0x1686590, 0xc0000b9ce0}, 0xc000496800)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/gunziphandler.go:26 +0xe9\nnet/http.HandlerFunc.ServeHTTP(0xedc03b331?, {0x1686590?, 0xc0000b9ce0?}, 0x35443cc41?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MaxBytesHandler.func2.1({0x1686590?, 0xc0000b9ce0?}, 0x1eaece0?)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/maxbyteshandler.go:24 +0xff\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x1686590?, 0xc0000b9ce0?}, 0x0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.MetricHandler.func1.1({0x1686590, 0xc0000b9ce0}, 0x0?)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/metrichandler.go:21 +0xd5\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x1686590?, 0xc0000b9ce0?}, 0x0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.RecoverHandler.func1({0x1686590?, 0xc0000b9ce0?}, 0x0?)\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/recoverhandler.go:21 +0x83\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x1686590?, 0xc0000b9ce0?}, 0x0?)\n\t/usr/local/go/src/net/http/server.go:2109 +0x2f\ngithub.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP.func1()\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:81 +0x7c\ncreated by github.com/zeromicro/go-zero/rest/handler.(*timeoutHandler).ServeHTTP\n\t/go/pkg/mod/github.com/zeromicro/go-zero@v1.5.2/rest/handler/timeouthandler.go:75 +0x350\n

**Comment by whyiyhw** [comment]
有发送的命令吗，比如 #prompt:set:25  我没法复现
#system 看看 系统版本信息
