### ISSUE TITLE
docker-compose -v 少了一个空格

### ISSUE THREAD

**Issue by JagoWang** [whyiyhw/chatgpt-wechat#69]
https://github.com/whyiyhw/chatgpt-wechat/blob/main/doc/install.md
第四步检查docker安装情况：
![WX20230530-210812@2x](https://github.com/whyiyhw/chatgpt-wechat/assets/1396829/a637a4b2-090b-439c-af24-84041efa1cdb)

docker-compose -v
|
docker -compose -v 
少了一个空格

**Comment by whyiyhw** [comment]
并没有哦，docker-compose 也是一个软件

**Comment by JagoWang** [comment]
> 

不好意思，搞错了，对docker不熟，docker-compose安装好了没有添加到path里，用docker -compose -v 可以输出版本号以为就是这个呢。。

**Comment by whyiyhw** [comment]
小问题，我补充了安装文档所在的链接
