### ISSUE TITLE
在自购服务器上 部署 golang 服务，并开启对外的网络端口

### ISSUE THREAD

**Issue by Angusvencent** [whyiyhw/chatgpt-wechat#7]
请问大佬第8步怎么具体操作

**Comment by whyiyhw** [comment]
先 git clone https://github.com/whyiyhw/chatgpt-wechat.git

**Comment by whyiyhw** [comment]
先 git clone https://github.com/whyiyhw/chatgpt-wechat.git

**Comment by whyiyhw** [comment]
先 git clone https://github.com/whyiyhw/chatgpt-wechat.git，然后 cd ./chatgpt-wechat , 剩下的步骤 就按照正常步骤走就好
