### ISSUE TITLE
关于聊天记录

### ISSUE THREAD

**Issue by sl05143** [whyiyhw/chatgpt-wechat#70]
老师，您好，请问部署以后运行成功，和客服的聊天记录是保存在哪里？

**Comment by whyiyhw** [comment]
部署时，启动了一个数据库，数据都在你本地的数据库内
数据库的账号，密码跟端口
都可以在 `chat/docker-compose.yml ` 内的数据库配置部分找到

**Comment by sl05143** [comment]
> 

太棒了，我用工具连接过去，找到了，感谢。

**Comment by whyiyhw** [comment]
♥️ 如果好用的话，就给个🌟 吧

**Comment by sl05143** [comment]
没问题！
