### ISSUE TITLE
debug模式无法使用

### ISSUE THREAD

**Issue by delphiduan** [whyiyhw/chatgpt-wechat#72]
V0.6.3.5配置文件启动debug: true ,实际并没有起作用

**Comment by whyiyhw** [comment]
> V0.6.3.5配置文件启动debug: true ,实际并没有起作用

如果是客服消息，确实没有用，因为客服消息一次请求，服务端只能回复5条数据，如果将 插件 debug 信息响应，就会导致正常的响应，可能被吞掉，所以客服消息，即使是开启debug ，也不会响应中间的插件处理信息

**Comment by delphiduan** [comment]
那是否可以打印在log里面？

**Comment by whyiyhw** [comment]
> 那是否可以打印在log里面？

目前只有请求，与响应信息log，基本也够用了，能看出来是否使用了插件，没有专门打印到log里面，电脑被我拆坏了，在等新的配件，到了我再强化下插件 log信息
