### ISSUE TITLE
企业微信客服设置接收事件服务器url必须要域名吗？

### ISSUE THREAD

**Issue by AnLingzhi** [whyiyhw/chatgpt-wechat#73]
企业微信客服设置接收事件服务器url必须要域名吗？我填http://ip:8887 输入框一直是红的，提示请填写带http或https协议头的合法URL

**Comment by whyiyhw** [comment]
不是必须的，如果你是未认证的企业微信，应该能直接用IP，已认证的就有点麻烦了，有域名的，解析二级域名就好，没域名的，可以尝试备案
不想备案，买一个域名解析到国外服务器也行，服务器在国内的，只能想办法把这域名请求解析到国外，再转发到国内服务器，很早之前的文档里面有用阿里云函数规避域名解析的操作
