### ISSUE TITLE
默认使用的模型是gpt-3.5-turbo-0301，为什么同时会有text-davinci模型的请求？

### ISSUE THREAD

**Issue by yangleimiao** [whyiyhw/chatgpt-wechat#74]
<img width="479" alt="截屏2023-06-10 18 57 55" src="https://github.com/whyiyhw/chatgpt-wechat/assets/32082157/9512cde6-02a3-48d4-83a6-f9b91591e956">
如图可看到同时有text-davinci和gpt-3.5-turbo-0301模型的请求，根据日志，可能是在chatgpt-wechat/chat/common/openai/context.go的doSummary函数，进行 summary 简化时使用的text-davinci模型；这个summary的作用是什么？text-davinci的计费是gpt-3.5-turbo-0301的10倍，这样是否会使费用增长？如何配置summary使用gpt-3.5-turbo-0301模型？

**Comment by yangleimiao** [comment]
<img width="359" alt="截屏2023-06-10 23 26 23" src="https://github.com/whyiyhw/chatgpt-wechat/assets/32082157/b64f04c8-3d29-42a1-b616-332b18a90796">
找到代码位置了，代码里写定的使用text-davinci模型，想问下为什么写定使用这个模型？好处是什么呢？如果要使用gpt-3.5-turbo模型，只能改代码重新编译是吗

**Comment by whyiyhw** [comment]
> <img alt="截屏2023-06-10 18 57 55" width="479" src="https://user-images.githubusercontent.com/32082157/244878723-9512cde6-02a3-48d4-83a6-f9b91591e956.png"> 如图可看到同时有text-davinci和gpt-3.5-turbo-0301模型的请求，根据日志，可能是在chatgpt-wechat/chat/common/openai/context.go的doSummary函数，进行 summary 简化时使用的text-davinci模型；这个summary的作用是什么？text-davinci的计费是gpt-3.5-turbo-0301的10倍，这样是否会使费用增长？如何配置summary使用gpt-3.5-turbo-0301模型？

1. 作用就是用来控制上下文长度并尽可能的保留对话的核心信息，我没

**Comment by whyiyhw** [comment]
> <img alt="截屏2023-06-10 18 57 55" width="479" src="https://user-images.githubusercontent.com/32082157/244878723-9512cde6-02a3-48d4-83a6-f9b91591e956.png"> 如图可看到同时有text-davinci和gpt-3.5-turbo-0301模型的请求，根据日志，可能是在chatgpt-wechat/chat/common/openai/context.go的doSummary函数，进行 summary 简化时使用的text-davinci模型；这个summary的作用是什么？text-davinci的计费是gpt-3.5-turbo-0301的10倍，这样是否会使费用增长？如何配置summary使用gpt-3.5-turbo-0301模型？

作用就是用来控制上下文长度并尽可能的保留对话的核心信息，2. 会的   3.暂不支持，可以考虑

**Comment by whyiyhw** [comment]
> <img alt="截屏2023-06-10 23 26 23" width="359" src="https://user-images.githubusercontent.com/32082157/244879160-b64f04c8-3d29-42a1-b616-332b18a90796.png"> 找到代码位置了，代码里写定的使用text-davinci模型，想问下为什么写定使用这个模型？好处是什么呢？如果要使用gpt-3.5-turbo模型，只能改代码重新编译是吗

相对于 3.5 ，3的扩展跟逻辑性都会强一下，所以使用了3去做一些逻辑相关的操作，比如说文本简化，插件判定... 2. 是的，我有空了测试用 3.5 替换 text ，没怎么在意这个消耗，因为平时就我跟几个朋友一起用

**Comment by yangleimiao** [comment]
明白了，感谢回答

**Comment by whyiyhw** [comment]
最新版本，已经统一调整为 gpt3 了，但是感觉效果会差一点点，不过也能接受，你试试
