### ISSUE TITLE
显示8888 端口被占用，启动失败

### ISSUE THREAD

**Issue by hellolufeng** [whyiyhw/chatgpt-wechat#76]
我用的是腾讯云+宝塔面板，宝塔面板默认端口 8888 无法修改，所以我在配置文件里把开头的8888 改为了 80（我用的是 ngnix 反代访问域名到服务器的 8887 端口），求大佬解答
错误如下：
Error response from daemon: driver failed programming external connectivity on endpoint chat-web-1 (250d4c1c1e5b8db8a5b197b875f4b4867a4e1aa877062293538f629155ceef4e): Error starting userland proxy: listen tcp4 0.0.0.0:8888: bind: address already in use
<img width="877" alt="Screenshot 2023-06-13 at 11 30 33" src="https://github.com/whyiyhw/chatgpt-wechat/assets/3109488/572ad54b-59ad-42b8-b122-16240b5aabc6">

**Comment by whyiyhw** [comment]
配置文件的不用改，`chat/docker-compose.yml` 这个里面 的 8888:8888 去掉就行
