### ISSUE TITLE
企微端上下文问题

### ISSUE THREAD

**Issue by chenbe1990** [whyiyhw/chatgpt-wechat#77]
使用企业微信端，因为不是每个人都会清理会话，导致每次对话都带上很多上下文内容，能否设置个超时时间，例如：超过一个小时的记录就不携带。

**Comment by whyiyhw** [comment]
新版本调整了 token 总结的策略，一般来说，上下文会被 summary 到 500字左右，跟固定2，3轮对话的上下文 token 差不多，对于丢弃长时间未活跃的会话，我有个想法，就是 会话时间做成配置（下个小版本做），你配成1个小时过期就行

**Comment by whyiyhw** [comment]
新版本加入了配置
```yml
Session:                                            # 会话相关配置
  Timeout: -1                                       # 会话超时时间（m）分钟，如果在（x）分钟内，未进行对话，本次会话内容会被销毁，-1为永不超时（可选）
```
你可以在完整配置文件中找到，修改为 60 就可以实现你目前的需求
