### ISSUE TITLE
我在使用宝塔部署这个应用时遇到了问题。

### ISSUE THREAD

**Issue by tanjingdong** [whyiyhw/chatgpt-wechat#82]
服务器环境是CentOS，宝塔面板。
由于服务器无法连接Github，我把你的Yaml文件内容复制到宝塔面板的Docker-compose中，却遇到了提示错误：

检测失败: In file '/www/server/panel/data/compose/企业微信ChatGPT回调服务/template/企业微信ChatGPT回调服务.yaml', service 'Name' must be a mapping not a string.

然后无论我怎么修改都无法获得正确的配置文件。我也尝试直接编辑一个yaml文件后运行，结果是无法拉取任何镜像。请教这到底是怎么回事？

**Comment by whyiyhw** [comment]
宝塔用户请自行探索

**Comment by tanjingdong** [comment]
> 宝塔用户请自行探索

我放弃了。由于企业微信对应用服务器新的限制，需要进行挺复杂的备案，而我的环境无法取得领导的理解完成备案，所以放弃了这个项目。我改用ChatGPT Next Web搭建了一个网页来用。将来有机会再用吧。用对聊天话框来解决其实真的是个不错的前端呢。
