### ISSUE TITLE
请问该应用能给企业之外的用户使用吗？

### ISSUE THREAD

**Issue by PetrusZ** [whyiyhw/chatgpt-wechat#83]
不好意思，之前没接触过企业微信的应用。

请问该应用能给企业之外的用户使用吗？还是说必须要将用户邀请进入企业后，才能使用这个应用

**Comment by whyiyhw** [comment]
可以呀，你可以看看客服消息文档，通过这个方式，可以在微信体系内用，无需关联企业微信
