### ISSUE TITLE
发送测试报错

### ISSUE THREAD

**Issue by irol765** [whyiyhw/chatgpt-wechat#86]
log:
Starting server at 0.0.0.0:8888...
incoming message: RxMessage { FromUserID: "irol765", SendTime: 1688239202000000000, MsgType: "text", MsgID: 7250932163377818155, AgentID: 0, Event: "", ChangeType: "", Content: "测试" }
ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:20:03.232+08:00 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:20:03.232+08:00 content=【API-ERR】 : ErrCode:400，ErrMsg:参数错误 ,应用标识为必填字段  ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:20:03.232+08:00 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:20:03.232+08:00 content=【API-ERR】 : ErrCode:400，ErrMsg:参数错误 ,应用标识为必填字段  span=febe78c24abe122e ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:20:03.232+08:00 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:20:03.232+08:00 content=【API-ERR】 : ErrCode:400，ErrMsg:参数错误 ,应用标识为必填字段  ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:20:03.232+08:00 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:20:03.232+08:00 content=【API-ERR】 : ErrCode:400，ErrMsg:参数错误 ,应用标识为必填字段  span=febe78c24abe122e trace=e37b525d742d62a60f9811878b346f4a
INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 content= INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 content= response={"code":400,"msg":"参数错误 ,应用标识为必填字段","data":{}} INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 content= INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 content= response={"code":400,"msg":"参数错误 ,应用标识为必填字段","data":{}} span=febe78c24abe122e INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 content= INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 content= response={"code":400,"msg":"参数错误 ,应用标识为必填字段","data":{}} INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 content= INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:20:03.232+08:00 content= response={"code":400,"msg":"参数错误 ,应用标识为必填字段","data":{}} span=febe78c24abe122e trace=e37b525d742d62a60f9811878b346f4a
INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 content= INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 content= request={"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"openai\",\"msg\":\"测试\",\"user_id\":\"irol765\",\"agent_id\":0}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQxNTkxNzYsImlhdCI6MTY4ODIzOTE3NiwidXNlcklkIjoxfQ.3pcM6XxFFxEW42AtByVv69JrJpZHjy3iReT6QWWbi1g"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":0} INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 content= INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 content= request={"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"openai\",\"msg\":\"测试\",\"user_id\":\"irol765\",\"agent_id\":0}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQxNTkxNzYsImlhdCI6MTY4ODIzOTE3NiwidXNlcklkIjoxfQ.3pcM6XxFFxEW42AtByVv69JrJpZHjy3iReT6QWWbi1g"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":0} span=febe78c24abe122e INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 content= INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 content= request={"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"openai\",\"msg\":\"测试\",\"user_id\":\"irol765\",\"agent_id\":0}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQxNTkxNzYsImlhdCI6MTY4ODIzOTE3NiwidXNlcklkIjoxfQ.3pcM6XxFFxEW42AtByVv69JrJpZHjy3iReT6QWWbi1g"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":0} INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 content= INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:20:03.232+08:00 content= request={"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"openai\",\"msg\":\"测试\",\"user_id\":\"irol765\",\"agent_id\":0}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQxNTkxNzYsImlhdCI6MTY4ODIzOTE3NiwidXNlcklkIjoxfQ.3pcM6XxFFxEW42AtByVv69JrJpZHjy3iReT6QWWbi1g"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":0} span=febe78c24abe122e trace=e37b525d742d62a60f9811878b346f4a
INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:59254 - Go-http-client/1.1 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:59254 - Go-http-client/1.1 duration=1.3ms INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:59254 - Go-http-client/1.1 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:59254 - Go-http-client/1.1 duration=1.3ms span=febe78c24abe122e INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:59254 - Go-http-client/1.1 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:59254 - Go-http-client/1.1 duration=1.3ms INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:59254 - Go-http-client/1.1 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:20:03.233+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:59254 - Go-http-client/1.1 duration=1.3ms span=febe78c24abe122e trace=e37b525d742d62a60f9811878b346f4a
incoming message: RxMessage { FromUserID: "irol765", SendTime: 1688239540000000000, MsgType: "text", MsgID: 7250933612393354027, AgentID: 0, Event: "", ChangeType: "", Content: "测试" }
ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:25:40.661+08:00 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:25:40.661+08:00 content=【API-ERR】 : ErrCode:400，ErrMsg:参数错误 ,应用标识为必填字段  ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:25:40.661+08:00 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:25:40.661+08:00 content=【API-ERR】 : ErrCode:400，ErrMsg:参数错误 ,应用标识为必填字段  span=cdc7c1646d1576b5 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:25:40.661+08:00 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:25:40.661+08:00 content=【API-ERR】 : ErrCode:400，ErrMsg:参数错误 ,应用标识为必填字段  ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:25:40.661+08:00 ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > ERR ERR response/response.go:42 > @timestamp=2023-07-02T03:25:40.661+08:00 content=【API-ERR】 : ErrCode:400，ErrMsg:参数错误 ,应用标识为必填字段  span=cdc7c1646d1576b5 trace=143929eb01728bf1831c0e5e5b7cd517
INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 content= INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 content= response={"code":400,"msg":"参数错误 ,应用标识为必填字段","data":{}} INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 content= INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 content= response={"code":400,"msg":"参数错误 ,应用标识为必填字段","data":{}} span=cdc7c1646d1576b5 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 content= INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 content= response={"code":400,"msg":"参数错误 ,应用标识为必填字段","data":{}} INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 content= INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > INF INF response/response.go:63 > @timestamp=2023-07-02T03:25:40.661+08:00 content= response={"code":400,"msg":"参数错误 ,应用标识为必填字段","data":{}} span=cdc7c1646d1576b5 trace=143929eb01728bf1831c0e5e5b7cd517
INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 content= INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 content= request={"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"openai\",\"msg\":\"测试\",\"user_id\":\"irol765\",\"agent_id\":0}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQxNTkxNzYsImlhdCI6MTY4ODIzOTE3NiwidXNlcklkIjoxfQ.3pcM6XxFFxEW42AtByVv69JrJpZHjy3iReT6QWWbi1g"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":0} INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 content= INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 content= request={"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"openai\",\"msg\":\"测试\",\"user_id\":\"irol765\",\"agent_id\":0}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQxNTkxNzYsImlhdCI6MTY4ODIzOTE3NiwidXNlcklkIjoxfQ.3pcM6XxFFxEW42AtByVv69JrJpZHjy3iReT6QWWbi1g"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":0} span=cdc7c1646d1576b5 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 content= INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 content= request={"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"openai\",\"msg\":\"测试\",\"user_id\":\"irol765\",\"agent_id\":0}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQxNTkxNzYsImlhdCI6MTY4ODIzOTE3NiwidXNlcklkIjoxfQ.3pcM6XxFFxEW42AtByVv69JrJpZHjy3iReT6QWWbi1g"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":0} INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 content= INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > INF INF accesslog/accesslog.go:29 > @timestamp=2023-07-02T03:25:40.661+08:00 content= request={"url":"/api/msg/push","method":"POST","query":"","body":"{\"channel\":\"openai\",\"msg\":\"测试\",\"user_id\":\"irol765\",\"agent_id\":0}","header":{"Accept-Encoding":["gzip"],"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQxNTkxNzYsImlhdCI6MTY4ODIzOTE3NiwidXNlcklkIjoxfQ.3pcM6XxFFxEW42AtByVv69JrJpZHjy3iReT6QWWbi1g"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]},"const":0} span=cdc7c1646d1576b5 trace=143929eb01728bf1831c0e5e5b7cd517
INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:47550 - Go-http-client/1.1 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:47550 - Go-http-client/1.1 duration=0.6ms INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:47550 - Go-http-client/1.1 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:47550 - Go-http-client/1.1 duration=0.6ms span=cdc7c1646d1576b5 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:47550 - Go-http-client/1.1 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:47550 - Go-http-client/1.1 duration=0.6ms INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:47550 - Go-http-client/1.1 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > INF INF handler/loghandler.go:160 > @timestamp=2023-07-02T03:25:40.661+08:00 content=[HTTP] 200 - POST /api/msg/push - 127.0.0.1:47550 - Go-http-client/1.1 duration=0.6ms span=cdc7c1646d1576b5 trace=143929eb01728bf1831c0e5e5b7cd517

麻烦指点

**Comment by irol765** [comment]
我发现了，我有个默认的应用AgentId是0的叫企业小助手，这个不用设置白名单，但是这个接入后发测试就报错，新建其他有7位id的应用就能正常使用。

**Comment by whyiyhw** [comment]
应该是你应用id 配置的问题
