### ISSUE TITLE
gpt-4 不存在

### ISSUE THREAD

**Issue by Sun-Jingjun** [whyiyhw/chatgpt-wechat#92]
我的账号已经是api付费用户：
![image](https://github.com/whyiyhw/chatgpt-wechat/assets/55533902/efff4855-ff10-4b47-bda7-b625ea29c0f3)

但是还是没有gpt-4的权限。
我看openai更新日志，目前所有的付费用户应该都有了这个权限

我看了下我们的账号，是有成功的付费记录的：
![image](https://github.com/whyiyhw/chatgpt-wechat/assets/55533902/b18c42b3-929a-42d4-98d0-097803f25aac)

**Comment by Sun-Jingjun** [comment]
大佬帮忙看下这里的问题，还有就是有没有群之类的，可以更快速沟通交流的

**Comment by Sun-Jingjun** [comment]
配置文件是这样的
![image](https://github.com/whyiyhw/chatgpt-wechat/assets/55533902/a768b9c9-cb0a-482a-bdb9-44b22c79297b)

**Comment by whyiyhw** [comment]
最好不要在评论区贴配置😓 小心点，用绑定了信用卡的号再试试呢
