### ISSUE TITLE
企微welcome消息不生效

### ISSUE THREAD

**Issue by wdlid** [whyiyhw/chatgpt-wechat#96]
如下配置，进入应用的时候log可以看到发送了#welcome指令，但是收不到消息。

WeCom:
  CorpID: "xxxxxxxxx"                  # 企业微信CorpID
  DefaultAgentSecret: "yyyyyyyyyyyyyyyyyyyyyy"
  Token: "zzzzzzzzzzzzzzzzzzzz"                               # 企业微信应用/客服消息 Token
  EncodingAESKey: "aaaaaaaaaaaaaaaaaaaaaaaaa"                # 企业微信应用/客服消息 EncodingAESKey  
  Welcome: "您好！我是 ChatGPT，一个由 OpenAI 训练的大型语言模型，我可以回答您的问题和进行交流。请告诉我您需要了解些什么，我会尽力为您提供答案。"  # 进入应用时的欢迎语

log：
incoming message: RxMessage { FromUserID: "aaaa", SendTime: 1694743320000000000, MsgType: "event", MsgID: 0, AgentID: 1000008, Event: "enter_agent", ChangeType: "", Raw: "<xml><ToUserName><![CDATA[ww53adfefaeeedff]]></ToUserName><FromUserName><![CDATA[aaaa]]></FromUserName><CreateTime>1694743320</CreateTime><MsgType><![CDATA[event]]></MsgType><AgentID>1000008</AgentID><Event><![CDATA[**enter_agent**]]></Event><EventKey><![CDATA[]]></EventKey></xml>" }

**Comment by whyiyhw** [comment]
这个消息第一次发送后，会被缓存在 `redis` 中，默认是15天才发送一次
