### ISSUE TITLE
请教企业微信客服功能

### ISSUE THREAD

**Issue by aiyurui** [whyiyhw/chatgpt-wechat#99]
不知道是不是个人企业微信的原因，微信客服里没有“接收事件服务器”的选项，在“可调用接口的应用”中调用已经部署成功的机器人应用也无法生效，机器人收不到来自客服对话的消息。

**Comment by aiyurui** [comment]
![WeChat截图_20231205014047](https://github.com/whyiyhw/chatgpt-wechat/assets/79858074/f9a0c526-09f5-4006-9210-3ceced202cb6)

**Comment by Magicat-CX** [comment]
微信客服好像完全改掉了，推送的事件跟原来的不一样了

**Comment by Magicat-CX** [comment]
企微客服现在改成和应用跟客服账号绑定了

**Comment by ensonfun** [comment]
同样遇到这个问题，需要升级代码才能解决吗？感觉应该是要响应下客服号的接待事件

**Comment by luohao123** [comment]
这个是不是无法出现在正常对话列表，而是收纳在客服消息里面？

**Comment by whyiyhw** [comment]
已修复，配置与文档已更新
